version: '3.1'

services:
  webserver:
    image: jeffdesouza/rails-proxy
    ports:
      - 80:80
    links:
      - app
    depends_on:
      - app
  
  db:
    image: postgres:9.4.1
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-pass
    secrets:
      - db-pass
    volumes:
      - psql-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    links:
      - db:db
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin
      PGADMIN_DEFAULT_PASSWORD: 123
    depends_on:
      - db
  
  app:
    build: .
    entrypoint:
      - /usr/bin/change_app_root_directory
      - /usr/bin/remove_server_pid
      - /usr/bin/run_migrate
    command: bin/rails server --port 3000 --binding 0.0.0.0
    links:
      - db
    volumes:
      - ./rails-app:/usr/src/app
    ports:
      - 3000
    depends_on:
      - db

volumes:
  psql-data:
  pgadmin:

secrets:
  db-pass:
    file: './docker/secrets/db-pass'